version: '3.8'
services:
  redmine:
    # image: redmine:5.1.4
    build: .
    ports:
      - 8080:3000
    volumes: 
      - greenmine-files:/usr/src/redmine/files
      - ./plugins:/usr/src/redmine/plugins
      - ./configuration.yml:/usr/src/redmine/config/configuration.yml:rw
      - ./cable.yml:/usr/src/redmine/config/cable.yml:rw
      - type: bind
        source: ./docker-entrypoint.sh
        target: /docker-entrypoint.sh
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: redmine
      REDMINE_SECRET_KEY_BASE: UDWWZ4TeoaopkXi7YT2YVzN
      REDMINE_PLUGINS_MIGRATE: "1"
      REDIS_URL: redis://redis:6379/0
      REDMINE_ENABLE_CRONS: "1"
      VITE_BASE_URL: http://127.0.0.1:8111
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
    ports:
      - 8866:3306
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
  smtp:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: redmine

volumes:
  greenmine-files:
    driver: local
  redis:
    driver: local